env:
  token: ${{ secrets.ACCESS_TOKEN }}

name: Create-Incident
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Debug Info
        run: |
          echo "Running Debug Info"
          env
        shell: bash

      - uses: actions/checkout@v2

      - name: Retrieve Workflow Run ID
        run: |
          echo "Workflow Run ID: ${{ env.WORKFLOW_RUN_ID }}"
          # Store the Workflow Run ID in a variable
          WORKFLOW_RUN_ID="${{ env.WORKFLOW_RUN_ID }}"
      
      - name: Get Latest Commit Message
        id: get-commit-message
        run: |
          commitMessage=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                         "https://api.github.com/repos/${{ github.repository }}/commits?per_page=1" | \
                         jq -r '.[0].commit.message')
          echo "::set-output name=commit-message::$commitMessage"

      - name: Check Commit Message
        id: check-message
        run: |
          commitMessage="${{ steps.get-commit-message.outputs.commit-message }}"
          if [[ "$commitMessage" == "workflow2" ]]; then
            echo "Commit message is 'workflow2'. Stopping the workflow."
            exit 1
          else
            echo "Commit message is not 'workflow2'. Continuing with the workflow."
          fi

      - name: Check Workflow Run ID
        run: |
          if [[ "${{ github.run_id }}" == "$WORKFLOW_RUN_ID" ]]; then
            echo "Skipping further execution to break the loop."
            exit 0
          fi
      - name: Run Checks
        id: run-checks
        run: |
          # Perform your checks here
          # Access the SHA from the previous workflow output
          commitSha=$(echo "${{ needs.get-sha.outputs.commit-sha }}")
          echo "The commit SHA is $commitSha"

      - name: Stop Workflow
        if: ${{ steps.run-checks.outputs.commitSha == github.sha }}
        run: echo "Stopping workflow because the SHA matches" 
             exit 0
        
        
      - name: Run script file
        run: |
          echo "Running package2dependency.sh"
          chmod +x ./package2dependency.sh
          ./package2dependency.sh
          
          echo "Running check_latest.sh"
          chmod +x ./check_latest.sh
          ./check_latest.sh
        shell: bash

      - name: create issue
        run: |
          echo "Running Create_Issue.sh"
          chmod +x ./Create_Issue.sh
          ./Create_Issue.sh
        shell: bash
